name: "CI Tests"
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-24.04
    name: "Elixir ${{matrix.elixir}} OTP ${{matrix.otp}}"
    strategy:
      fail-fast: false
      matrix:
        otp: [24.3, 25.3, 26.2]
        elixir: [1.14.5, 1.15.7, 1.16.2, 1.17.3, 1.18.1]
        exclude:
          - elixir: 1.14.5
            otp: 26.2
          - elixir: 1.11.4
            otp: 25.3
          - elixir: 1.12.3
            otp: 25.3
          - elixir: 1.14.5
            otp: 25.3
          - elixir: 1.15.7
            otp: 23.3
          - elixir: 1.15.7
            otp: 24.3
          - elixir: 1.16.2
            otp: 24.3
          - elixir: 1.17.3
            otp: 24.3
          - elixir: 1.18.1
            otp: 24.3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix test
      - run: ./test/runtime_warnings.sh
      - run: ./test/smoke_test.sh
