name: "Compatibility: Phoenix"
on:
  push:
    branches:
      - master
      - release/*

jobs:
  test_on_source:
    runs-on: ubuntu-20.04
    name: "Elixir ${{matrix.elixir}} OTP ${{matrix.otp}} - ${{matrix.repo_branch}}"
    strategy:
      fail-fast: false
      matrix:
        repo_url: ["https://github.com/phoenixframework/phoenix.git"]
        repo_branch: ["v1.6", "main"]
        otp: [23.3, 24.3, 25.3, 26.1]
        elixir: [1.11.4, 1.12.3, 1.13.4, 1.14.5, 1.15.7, 1.16.0]
        exclude:
          - elixir: 1.11.4
            otp: 26.1
          - elixir: 1.12.3
            otp: 26.1
          - elixir: 1.13.4
            otp: 26.1
          - elixir: 1.14.5
            otp: 26.1
          - elixir: 1.11.4
            otp: 25.3
          - elixir: 1.12.3
            otp: 25.3
          - elixir: 1.14.5
            otp: 25.3
          - elixir: 1.15.7
            otp: 23.3
          - elixir: 1.15.7
            otp: 24.3
          - elixir: 1.16.0
            otp: 23.3
          - elixir: 1.16.0
            otp: 24.3
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mkdir -p tmp
      - run: git clone ${{matrix.repo_url}} tmp/${{matrix.repo_branch}} --depth=1 --branch ${{matrix.repo_branch}}
      - run: mix credo tmp/${{matrix.repo_branch}} --strict --mute-exit-status

  test_on_new_project:
    runs-on: ubuntu-20.04
    name: "[${{matrix.otp}}/${{matrix.elixir}}] new Phoenix app analysed by Credo [OTP/Elixir]"
    strategy:
      matrix:
        otp: [23.3, 24.3, 25.3, 26.1]
        # phx_new depends on newer versions of Elixir than Credo
        elixir: [1.14.5, 1.15.7, 1.16.0]
        exclude:
          - elixir: 1.11.4
            otp: 26.1
          - elixir: 1.12.3
            otp: 26.1
          - elixir: 1.13.4
            otp: 26.1
          - elixir: 1.14.5
            otp: 26.1
          - elixir: 1.11.4
            otp: 25.3
          - elixir: 1.12.3
            otp: 25.3
          - elixir: 1.14.5
            otp: 25.3
          - elixir: 1.15.7
            otp: 23.3
          - elixir: 1.15.7
            otp: 24.3
          - elixir: 1.16.0
            otp: 23.3
          - elixir: 1.16.0
            otp: 24.3
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: ./test/test_phoenix_compatibility.sh
