name: "Housekeeping"
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  format:
    name: "used mix format"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2
          elixir-version: 1.16.2
      - run: mix deps.get
      - run: mix compile
      - run: ./test/check_formatted.sh

  trigger:
    name: "tested that for each check there is at least one trigger assertion"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2
          elixir-version: 1.16.2
      - run: mix deps.get
      - run: mix test test/credo/check/housekeeping_trigger.exs

  params:
    name: "tested that for each check all params are covered by tests"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2
          elixir-version: 1.16.2
      - run: mix deps.get
      - run: mix test test/credo/check/housekeeping_params.exs

  assert_triggers:
    name: "all triggers are looked up and confirmed"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2
          elixir-version: 1.16.2
      - run: mix deps.get
      - run: ASSERT_TRIGGERS=1 mix test

  compare_to_latest_credo:
    name: "resulting issues are still the same (optional)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2
          elixir-version: 1.16.2
      - run: mix deps.get
      - run: mix credo
      - run: mkdir tmp
      - run: elixir test/old_credo.exs > tmp/old_credo.txt
      - run: mix credo --strict --enable-disabled-checks .+ --no-color --format oneline > tmp/new_credo.txt
      - run: diff tmp/old_credo.txt tmp/new_credo.txt

